name: 'Jest'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  jest:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create environment file
        run: cp .env.example .env.test

      - name: Run tests
        run: npm run test
